### ISSUE TITLE
Can I run this project in an m1 MacBook environment?

### ISSUE THREAD

**Issue by xeounxzxu** [infobip/infobip-testcontainers-spring-boot-starter#17]
hello. 

I want to run this project on my MacBook m1, but it doesn't seem to run. 

I think for docker to work properly on m1 MacBook you need to use "platform: linux/amd64" and that's because I don't have the setting. 

We tested it with an Intel MacBook and confirmed that it worked normally. 

I wonder if support is available.

**Comment by lpandzic** [comment]
It works on M1 Mac with use of Colima. I'm running M1 Mac daily and the only issue I have is regarding mssqlserver.
For mssqlserver specifically I use 
`colima start --vm-type=vz --vz-rosetta --cpu 8 --memory 8 --disk 10 --network-addres` 
to run locally on M1. 

Lately there was some issue with colima upgrade and older mssql container so I upgraded it to 2019-latest in release I'm about to do so that's fixed as well.

**Comment by xeounxzxu** [comment]
@lpandzic 
Thanks for your reply. 
If you have any additional questions after checking the project, we will contact you. 
thank you
